"""fix_resume_indices

Revision ID: 4dd5cc025afe
Revises: 
Create Date: 2025-03-05 12:22:10.556662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd5cc025afe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_id', table_name='resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_resumes_id', 'resumes', ['id'], unique=False)
    # ### end Alembic commands ###
