"""Update Resume model for PDF extraction

Revision ID: 9ee482d12662
Revises: c8a2d2fed5b6
Create Date: 2025-02-25 15:51:04.295618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee482d12662'
down_revision: Union[str, None] = 'c8a2d2fed5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
