"""Add profile type and is_active to resume

Revision ID: c8a2d2fed5b6
Revises: f89085b245dd
Create Date: 2025-02-25 15:40:35.133853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a2d2fed5b6'
down_revision: Union[str, None] = 'f89085b245dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('profile_type', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('primary_languages', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('frameworks', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('seniority', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('industry_focus', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_active')
    op.drop_column('resumes', 'industry_focus')
    op.drop_column('resumes', 'seniority')
    op.drop_column('resumes', 'frameworks')
    op.drop_column('resumes', 'primary_languages')
    op.drop_column('resumes', 'profile_type')
    # ### end Alembic commands ###
