"""Initial migration

Revision ID: f89085b245dd
Revises: 
Create Date: 2025-02-25 14:05:29.885288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89085b245dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_info', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('name', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('email', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('years_experience', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('education', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('recent_job', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('recent_company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'recent_company')
    op.drop_column('resumes', 'recent_job')
    op.drop_column('resumes', 'education')
    op.drop_column('resumes', 'years_experience')
    op.drop_column('resumes', 'skills')
    op.drop_column('resumes', 'phone')
    op.drop_column('resumes', 'email')
    op.drop_column('resumes', 'name')
    op.drop_column('resumes', 'extracted_info')
    # ### end Alembic commands ###
